import "../register-secrets.js";
import { getOrgContext } from "@agent-native/core/org";
import {
  createAgentChatPlugin,
  loadActionsFromStaticRegistry,
} from "@agent-native/core/server";

// Static-import registry generated by @agent-native/core's Vite plugin at
// build time. Using a static import ensures bundlers (Nitro on Netlify,
// Vercel, AWS-Lambda) include every action module in the server bundle —
// a runtime filesystem scan finds nothing in a bundled function, which is
// why `autoDiscoverActions` on its own produces 404s for action routes in
// production.
import actionsRegistry from "../../.generated/actions-registry.js";

const INITIAL_TOOL_NAMES = [
  "view-screen",
  "list-recordings",
  "search-recordings",
  "get-recording-player-data",
  "request-transcript",
  "create-recording",
  "import-loom-recording",
  "update-recording",
  "finalize-recording",
  "cleanup-transcript",
  "regenerate-summary",
  "regenerate-title",
  "regenerate-chapters",
  "trim-recording",
  "remove-silences",
  "remove-filler-words",
  "export-to-brain",
  "navigate",
  "refresh-list",
];

export default createAgentChatPlugin({
  appId: "clips",
  actions: loadActionsFromStaticRegistry(actionsRegistry),
  initialToolNames: INITIAL_TOOL_NAMES,
  extraContext: async () =>
    `<clips-transcript-guidance>
The transcript in view-screen is a bounded preview. When previewTruncated is true, its text is expected to end mid-sentence and is never evidence that transcription stopped early. Call get-recording-player-data before judging transcript completeness or quoting the full transcript. For a failed or pending transcript, use request-transcript with force=true. For an explicit fresh retry of an existing ready transcript, also pass regenerate=true. Agent-triggered retries are queued for the durable worker and return pending while processing.
</clips-transcript-guidance>`,
  resolveOrgId: async (event) => (await getOrgContext(event)).orgId,
});
