// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts

/** Compiled IIFE string for embedded-wheel.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const embeddedWheelBridgeScript: string = `"use strict";
(() => {
  // app/components/design/bridge/embedded-wheel.bridge.ts
  (function() {
    var enabled = __EMBEDDED_WHEEL_FORWARDING_ENABLED__;
    if (!enabled) return;
    function clamp(value, limit) {
      var number = Number(value) || 0;
      if (number > limit) return limit;
      if (number < -limit) return -limit;
      return number;
    }
    function onWheel(e) {
      e.preventDefault();
      e.stopPropagation();
      if (e.stopImmediatePropagation) e.stopImmediatePropagation();
      try {
        window.parent.postMessage(
          {
            type: "embedded-canvas-wheel",
            deltaX: clamp(e.deltaX, 240),
            deltaY: clamp(e.deltaY, 240),
            deltaZ: clamp(e.deltaZ, 240),
            deltaMode: e.deltaMode,
            clientX: e.clientX,
            clientY: e.clientY,
            ctrlKey: !!e.ctrlKey,
            metaKey: !!e.metaKey,
            shiftKey: !!e.shiftKey,
            altKey: !!e.altKey
          },
          "*"
        );
      } catch (_err) {
      }
    }
    var wheelTarget = document.documentElement || document.body || document;
    wheelTarget.addEventListener("wheel", onWheel, {
      passive: false,
      capture: true
    });
  })();
})();
`;
