// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts

/** Compiled IIFE string for hit-test.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const hitTestBridgeScript: string = `"use strict";
(() => {
  // app/components/design/bridge/hit-test.bridge.ts
  (function() {
    var BRIDGE_CONTAINER_TAGS = [
      "div",
      "section",
      "main",
      "header",
      "footer",
      "nav",
      "article",
      "aside",
      "form",
      "ul",
      "ol",
      "figure",
      "fieldset",
      "details",
      "dialog",
      "blockquote",
      "table",
      "tbody",
      "thead",
      "tr"
    ];
    var BRIDGE_LEAF_TAGS = [
      "img",
      "video",
      "picture",
      "audio",
      "canvas",
      "svg",
      "path",
      "input",
      "textarea",
      "select",
      "br",
      "hr",
      "iframe"
    ];
    var BRIDGE_TEXT_TAGS = [
      "p",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "span",
      "a",
      "strong",
      "em",
      "label",
      "li"
    ];
    function isOverlayElement(el) {
      return Boolean(
        el && el.closest && el.closest("[data-agent-native-edit-overlay]")
      );
    }
    function isLayerInteractionBlocked(el) {
      if (!el) return false;
      if (el.closest && el.closest(
        '[data-agent-native-locked="true"],[data-agent-native-hidden="true"]'
      ))
        return true;
      return false;
    }
    function isContainerDropTarget(el) {
      if (!el || el === document.documentElement) return false;
      if (isOverlayElement(el) || isLayerInteractionBlocked(el)) return false;
      if (el === document.body) return true;
      var tag = (el.tagName || "").toLowerCase();
      if (BRIDGE_LEAF_TAGS.indexOf(tag) !== -1 || BRIDGE_TEXT_TAGS.indexOf(tag) !== -1)
        return false;
      var cs = window.getComputedStyle(el);
      if (cs.display === "flex" || cs.display === "inline-flex" || cs.display === "grid" || cs.display === "inline-grid")
        return true;
      return BRIDGE_CONTAINER_TAGS.indexOf(tag) !== -1;
    }
    function elementFromEditorPoint(clientX, clientY) {
      var targets = document.elementsFromPoint ? document.elementsFromPoint(clientX, clientY) : [document.elementFromPoint(clientX, clientY)];
      for (var i = 0; i < targets.length; i += 1) {
        var target = targets[i];
        if (!target || target.nodeType !== 1) continue;
        if (isOverlayElement(target)) continue;
        if (isLayerInteractionBlocked(target)) return null;
        return target;
      }
      return null;
    }
    function parentFlowAxis(parent) {
      var cs = window.getComputedStyle(parent);
      if (cs.display === "flex" || cs.display === "inline-flex") {
        var isRow = cs.flexDirection && cs.flexDirection.indexOf("row") === 0;
        var wraps = cs.flexWrap === "wrap" || cs.flexWrap === "wrap-reverse";
        if (isRow && !wraps) return "x";
        return "y";
      }
      if (cs.display === "grid" || cs.display === "inline-grid") {
        var cols = (cs.gridTemplateColumns || "").split(" ").filter(Boolean).length;
        return cols > 1 ? "x" : "y";
      }
      return "y";
    }
    function edgePlacementForRect(rect, axis, clientX, clientY) {
      var size = axis === "x" ? rect.width : rect.height;
      if (!size) return null;
      var offset = axis === "x" ? clientX - rect.left : clientY - rect.top;
      if (offset < size * 0.22) return "before";
      if (offset > size * 0.78) return "after";
      return null;
    }
    function draggableElementChildren(parent) {
      return Array.prototype.slice.call(parent.children).filter(function(child) {
        return child.nodeType === 1 && !isOverlayElement(child) && !isLayerInteractionBlocked(child);
      });
    }
    function getNodeId(el) {
      if (!el) return "";
      return el.getAttribute("data-agent-native-node-id") || el.getAttribute("data-code-layer-id") || el.getAttribute("data-layer-id") || el.getAttribute("data-builder-id") || el.id || "";
    }
    function resolveHitTarget(clientX, clientY) {
      var hit = elementFromEditorPoint(clientX, clientY);
      if (!hit || hit === document.documentElement) return null;
      if (isContainerDropTarget(hit)) {
        var containerRect = hit.getBoundingClientRect();
        var edgeAxis = hit.parentElement ? parentFlowAxis(hit.parentElement) : parentFlowAxis(hit);
        var edgePlacement = edgePlacementForRect(
          containerRect,
          edgeAxis,
          clientX,
          clientY
        );
        if (!edgePlacement) {
          return { anchor: hit, placement: "inside" };
        }
        return { anchor: hit, placement: edgePlacement };
      }
      var hitParent = hit.parentElement;
      if (hitParent) {
        var hitAxis = parentFlowAxis(hitParent);
        var hitRect = hit.getBoundingClientRect();
        var hitCenter = hitAxis === "x" ? hitRect.left + hitRect.width / 2 : hitRect.top + hitRect.height / 2;
        var hitPointer = hitAxis === "x" ? clientX : clientY;
        return {
          anchor: hit,
          placement: hitPointer < hitCenter ? "before" : "after"
        };
      }
      if (hit === document.body || !hit.parentElement) {
        return { anchor: document.body, placement: "inside" };
      }
      return null;
    }
    window.addEventListener("message", function(e) {
      if (e.source !== window.parent) return;
      if (!e.data || e.data.type !== "agent-native:hit-test") return;
      var correlationId = e.data.correlationId;
      var x = Number(e.data.x);
      var y = Number(e.data.y);
      if (!correlationId) return;
      var result = resolveHitTarget(x, y);
      var anchorNodeId = result ? getNodeId(result.anchor) : "";
      var placement = result ? result.placement : "inside";
      try {
        window.parent.postMessage(
          {
            type: "agent-native:hit-test-result",
            correlationId,
            anchorNodeId,
            placement
          },
          "*"
        );
      } catch (_err) {
      }
    });
  })();
})();
`;
