// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts

/** Compiled IIFE string for motion-preview.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const motionPreviewBridgeScript: string = `"use strict";
(() => {
  // app/components/design/bridge/motion-preview.bridge.ts
  (function() {
    var loadedTracks = [];
    var touchedProps = {};
    var originalInlineValues = {};
    function camelizeProp(prop) {
      return String(prop).replace(/-([a-z])/g, function(_m, c) {
        return c.toUpperCase();
      });
    }
    function formatNum(n) {
      if (!Number.isFinite(n)) return "0";
      return (Math.round(n * 1e4) / 1e4).toString();
    }
    function clamp255(x) {
      return x < 0 ? 0 : x > 255 ? 255 : x;
    }
    function clamp01(x) {
      return x < 0 ? 0 : x > 1 ? 1 : x;
    }
    function parseAlpha(s) {
      if (typeof s === "string" && s.indexOf("%") >= 0)
        return parseFloat(s) / 100;
      return parseFloat(s);
    }
    function hueToRgb(p, q, h) {
      if (h < 0) h += 1;
      if (h > 1) h -= 1;
      if (h < 1 / 6) return p + (q - p) * 6 * h;
      if (h < 1 / 2) return q;
      if (h < 2 / 3) return p + (q - p) * (2 / 3 - h) * 6;
      return p;
    }
    function hslToRgb(h, s, l) {
      h = (h % 360 + 360) % 360 / 360;
      s = clamp01(s);
      l = clamp01(l);
      if (s === 0) return [l * 255, l * 255, l * 255];
      var q = l < 0.5 ? l * (1 + s) : l + s - l * s;
      var p = 2 * l - q;
      return [
        hueToRgb(p, q, h + 1 / 3) * 255,
        hueToRgb(p, q, h) * 255,
        hueToRgb(p, q, h - 1 / 3) * 255
      ];
    }
    function parseColor(str) {
      if (typeof str !== "string") return null;
      var s = str.trim();
      var hex = /^#([0-9a-fA-F]{3,8})$/.exec(s);
      if (hex) {
        var h = hex[1];
        if (h.length === 3 || h.length === 4) {
          return [
            parseInt(h.charAt(0) + h.charAt(0), 16),
            parseInt(h.charAt(1) + h.charAt(1), 16),
            parseInt(h.charAt(2) + h.charAt(2), 16),
            h.length === 4 ? parseInt(h.charAt(3) + h.charAt(3), 16) / 255 : 1
          ];
        }
        if (h.length === 6 || h.length === 8) {
          return [
            parseInt(h.slice(0, 2), 16),
            parseInt(h.slice(2, 4), 16),
            parseInt(h.slice(4, 6), 16),
            h.length === 8 ? parseInt(h.slice(6, 8), 16) / 255 : 1
          ];
        }
        return null;
      }
      var rgb = /^rgba?\\(([^)]+)\\)$/i.exec(s);
      if (rgb) {
        var rp = rgb[1].split(/[\\s,\\/]+/).filter(function(x) {
          return x.length;
        });
        if (rp.length >= 3) {
          return [
            parseFloat(rp[0]),
            parseFloat(rp[1]),
            parseFloat(rp[2]),
            rp.length >= 4 ? parseAlpha(rp[3]) : 1
          ];
        }
        return null;
      }
      var hsl = /^hsla?\\(([^)]+)\\)$/i.exec(s);
      if (hsl) {
        var hp = hsl[1].split(/[\\s,\\/]+/).filter(function(x) {
          return x.length;
        });
        if (hp.length >= 3) {
          var c = hslToRgb(
            parseFloat(hp[0]),
            parseFloat(hp[1]) / 100,
            parseFloat(hp[2]) / 100
          );
          return [c[0], c[1], c[2], hp.length >= 4 ? parseAlpha(hp[3]) : 1];
        }
        return null;
      }
      return null;
    }
    function lerpColorArr(a, b, ratio) {
      return [
        a[0] + (b[0] - a[0]) * ratio,
        a[1] + (b[1] - a[1]) * ratio,
        a[2] + (b[2] - a[2]) * ratio,
        a[3] + (b[3] - a[3]) * ratio
      ];
    }
    function formatColor(c) {
      var r = Math.round(clamp255(c[0]));
      var g = Math.round(clamp255(c[1]));
      var b = Math.round(clamp255(c[2]));
      var a = clamp01(c[3]);
      if (a >= 1) return "rgb(" + r + ", " + g + ", " + b + ")";
      return "rgba(" + r + ", " + g + ", " + b + ", " + Math.round(a * 1e3) / 1e3 + ")";
    }
    function tokenizeSegments(str) {
      if (typeof str !== "string") return null;
      var segs = [];
      var i = 0;
      var n = str.length;
      var litStart = 0;
      var colorRe = /^(#[0-9a-fA-F]{3,8}|rgba?\\([^)]*\\)|hsla?\\([^)]*\\))/i;
      var numRe = /^[+-]?(?:\\d+\\.?\\d*|\\.\\d+)/;
      while (i < n) {
        var rest = str.slice(i);
        var cm = colorRe.exec(rest);
        if (cm) {
          var parsed = parseColor(cm[0]);
          if (parsed) {
            if (i > litStart) segs.push({ lit: str.slice(litStart, i) });
            segs.push({ type: "color", value: parsed });
            i += cm[0].length;
            litStart = i;
            continue;
          }
        }
        var prevCh = i > 0 ? str.charAt(i - 1) : "";
        if (!/[a-zA-Z]/.test(prevCh)) {
          var nm = numRe.exec(rest);
          if (nm) {
            var numText = nm[0];
            var unit = "";
            var um = /^[a-z%]+/i.exec(str.slice(i + numText.length));
            if (um) unit = um[0];
            if (i > litStart) segs.push({ lit: str.slice(litStart, i) });
            segs.push({ type: "num", value: parseFloat(numText), unit });
            i += numText.length + unit.length;
            litStart = i;
            continue;
          }
        }
        i++;
      }
      if (n > litStart) segs.push({ lit: str.slice(litStart, n) });
      return segs;
    }
    function segShape(segs) {
      var parts = [];
      for (var i = 0; i < segs.length; i++) {
        var s = segs[i];
        parts.push("lit" in s ? "L" + s.lit : "T" + s.type);
      }
      return parts.join("\\0");
    }
    function lerp(a, b, ratio) {
      a = a == null ? "" : String(a);
      b = b == null ? "" : String(b);
      if (a === b) return a;
      var ca = parseColor(a);
      var cb = parseColor(b);
      if (ca && cb) return formatColor(lerpColorArr(ca, cb, ratio));
      var aSegs = tokenizeSegments(a);
      var bSegs = tokenizeSegments(b);
      if (aSegs && bSegs && aSegs.length === bSegs.length && segShape(aSegs) === segShape(bSegs)) {
        var out = "";
        var ok = true;
        var touched = false;
        for (var k = 0; k < aSegs.length; k++) {
          var seg = aSegs[k];
          if ("lit" in seg) {
            out += seg.lit;
            continue;
          }
          var other = bSegs[k];
          if (!other || !("type" in other) || other.type !== seg.type) {
            ok = false;
            break;
          }
          touched = true;
          if (seg.type === "color" && "value" in seg && "value" in other) {
            out += formatColor(
              lerpColorArr(
                seg.value,
                other.value,
                ratio
              )
            );
          } else if ("value" in seg && "value" in other) {
            var unit = ("unit" in seg ? seg.unit : "") || ("unit" in other ? other.unit : "") || "";
            out += formatNum(
              seg.value + (other.value - seg.value) * ratio
            ) + unit;
          }
        }
        if (ok && touched) return out;
      }
      return ratio < 0.5 ? a : b;
    }
    function interpolate(keyframes, t) {
      if (!keyframes || keyframes.length === 0) return "";
      if (keyframes.length === 1) return keyframes[0].value;
      var prev = keyframes[0];
      var next = keyframes[keyframes.length - 1];
      for (var i = 0; i < keyframes.length - 1; i++) {
        if (t >= keyframes[i].t && t <= keyframes[i + 1].t) {
          prev = keyframes[i];
          next = keyframes[i + 1];
          break;
        }
      }
      var span = next.t - prev.t;
      if (span <= 0) return prev.value;
      var ratio = Math.max(0, Math.min(1, (t - prev.t) / span));
      return lerp(prev.value, next.value, ratio);
    }
    function applyPreview(t) {
      for (var i = 0; i < loadedTracks.length; i++) {
        var track = loadedTracks[i];
        var el = document.querySelector(
          '[data-agent-native-node-id="' + track.targetNodeId + '"]'
        );
        if (!el) continue;
        var value = interpolate(track.keyframes, t);
        if (value === "") continue;
        var prop = camelizeProp(track.property);
        if (!originalInlineValues[track.targetNodeId])
          originalInlineValues[track.targetNodeId] = {};
        if (!(prop in originalInlineValues[track.targetNodeId])) {
          originalInlineValues[track.targetNodeId][prop] = el.style[prop] || "";
        }
        el.style[prop] = value;
        if (!touchedProps[track.targetNodeId])
          touchedProps[track.targetNodeId] = [];
        if (touchedProps[track.targetNodeId].indexOf(prop) === -1) {
          touchedProps[track.targetNodeId].push(prop);
        }
      }
    }
    function clearPreview() {
      var nodeIds = Object.keys(touchedProps);
      for (var i = 0; i < nodeIds.length; i++) {
        var el = document.querySelector(
          '[data-agent-native-node-id="' + nodeIds[i] + '"]'
        );
        if (!el) continue;
        var props = touchedProps[nodeIds[i]];
        for (var j = 0; j < props.length; j++) {
          var originals = originalInlineValues[nodeIds[i]] || {};
          el.style[props[j]] = Object.prototype.hasOwnProperty.call(originals, props[j]) ? originals[props[j]] : "";
        }
      }
      touchedProps = {};
      originalInlineValues = {};
      loadedTracks = [];
    }
    window.addEventListener("message", function(e) {
      if (e.source !== window.parent) return;
      if (!e.data || typeof e.data.type !== "string") return;
      if (e.data.type === "motion-load-tracks") {
        clearPreview();
        loadedTracks = Array.isArray(e.data.tracks) ? e.data.tracks : [];
        return;
      }
      if (e.data.type === "motion-preview") {
        var t = Number(e.data.t);
        if (!Number.isFinite(t)) return;
        t = Math.max(0, Math.min(1, t));
        applyPreview(t);
        return;
      }
      if (e.data.type === "motion-preview-clear") {
        clearPreview();
        return;
      }
    });
  })();
})();
`;
