// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts

/** Compiled IIFE string for shader-fill-preview.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const shaderFillPreviewBridgeScript: string = `"use strict";
(() => {
  // app/components/design/bridge/shader-fill-preview.bridge.ts
  (function() {
    var patchedEl = null;
    var originalBackground = "";
    function resolveTarget(selector, nodeId) {
      if (selector) {
        try {
          var hit = document.querySelector(selector);
          if (hit) return hit;
        } catch (_err) {
        }
      }
      if (nodeId) {
        var byId = document.querySelector(
          '[data-agent-native-node-id="' + nodeId.replace(/"/g, '\\\\"') + '"]'
        );
        if (byId) return byId;
      }
      return document.body;
    }
    function applyPreview(selector, nodeId, css) {
      clearPreview();
      var el = resolveTarget(selector, nodeId);
      if (!el) return;
      originalBackground = el.style.background || "";
      el.style.background = css || "";
      patchedEl = el;
    }
    function clearPreview() {
      if (!patchedEl) return;
      patchedEl.style.background = originalBackground;
      patchedEl = null;
      originalBackground = "";
    }
    window.addEventListener("message", function(e) {
      if (e.source !== window.parent) return;
      if (!e.data || typeof e.data.type !== "string") return;
      if (e.data.type === "shader-fill-preview") {
        var selector = typeof e.data.selector === "string" ? e.data.selector : "";
        var nodeId = typeof e.data.nodeId === "string" ? e.data.nodeId : "";
        var css = typeof e.data.css === "string" ? e.data.css : "";
        applyPreview(selector, nodeId, css);
        return;
      }
      if (e.data.type === "shader-fill-preview-clear") {
        clearPreview();
        return;
      }
    });
  })();
})();
`;
