// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts

/** Compiled IIFE string for tweak.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const tweakBridgeScript: string = `"use strict";
(() => {
  // app/components/design/bridge/tweak.bridge.ts
  (function() {
    window.addEventListener("message", function(e) {
      if (e.source !== window.parent) return;
      if (!e.data || e.data.type !== "tweak-values") return;
      var root = document.documentElement;
      var vals = e.data.values || {};
      Object.keys(vals).forEach(function(k) {
        root.style.setProperty(k, vals[k]);
      });
    });
  })();
})();
`;
